baseURL = 'https://blog.hwajin.me/'
languageCode = 'ja-JP'
title = "Hwajin's Blog."
paginate = 10
defaultContentLanguage = 'ja'
defaultContentLanguageInSubdir = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  readingTime = true

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = true

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default
  [params.giscus]
    repo = "hwajin-me/blog.hwajin.me"
    repoID = "MDEwOlJlcG9zaXRvcnkyNDUzNTI0Mjk="
    category = "General"
    categoryID = "DIC_kwDODp_H7c4COW6Q"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "1"
    inputPosition = "bottom"
    theme = "dark_high_contrast"
    lang = "en"
    loading = "lazy"

[services]
  [services.googleAnalytics]
    ID = 'G-LJWJ9LNV2L'

[languages]

  [languages.ko]
    disabled = false
    languageName = "🇰🇷 Korean"
    title = "Hwajin's Blog"
    weight = 2
    [languages.ko.params]
      subtitle = "Software Engineering, Hwajin's personal blog."
      owner = "Hwajin Lee"
      keywords = "Software Engineering,Develop,Backend Engineer,Spring,Java,PHP"
      copyright = "Hwajin Lee"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.ko.params.logo]
        logoText = "Hwajin's Blog"
        logoHomeLink = "/"

      [languages.ko.menu]
        [[languages.ko.menu.main]]
          identifier = "about"
          name = "About"
          url = "/ko/about"

        [[languages.ko.menu.main]]
          identifier = "linkedin"
          name = "Linkedin"
          url = "https://www.linkedin.com/in/hwajin-me/"

        [[languages.ko.menu.main]]
          identifier = "github"
          name = "Github"
          url = "https://github.com/hwajin-me"

  [languages.ja]
    disabled = false
    languageName = "🇯🇵 Japanese"
    title = "Hwajin's Blog"
    weight = 1

    [languages.ja.params]
      subtitle = "Software Engineering, Hwajin's personal blog."
      owner = "Hwajin(和真) Lee"
      keywords = "Software Engineering,Develop,Backend Engineer,Spring,Java,PHP"
      copyright = "Hwajin Lee"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.ja.params.logo]
        logoText = "Hwajin's Blog"
        logoHomeLink = "/"

      [languages.ja.menu]
        [[languages.ja.menu.main]]
          identifier = "about"
          name = "About"
          url = "/ja/about"

        [[languages.ja.menu.main]]
          identifier = "linkedin"
          name = "Linkedin"
          url = "https://www.linkedin.com/in/hwajin-me/"

        [[languages.ja.menu.main]]
          identifier = "github"
          name = "Github"
          url = "https://github.com/hwajin-me"

  [languages.en]
    disabled = false
    languageName = "🇺🇸 English"
    title = "Hwajin's Blog"
    weight = 3

    [languages.en.params]
      subtitle = "Software Engineering, Hwajin's personal blog."
      owner = "Hwajin Lee"
      keywords = "Software Engineering,Develop,Backend Engineer,Spring,Java,PHP"
      copyright = "Hwajin Lee"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Hwajin's Blog"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"

        [[languages.en.menu.main]]
          identifier = "linkedin"
          name = "Linkedin"
          url = "https://www.linkedin.com/in/hwajin-me/"

        [[languages.en.menu.main]]
          identifier = "github"
          name = "Github"
          url = "https://github.com/hwajin-me"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]

[module]
  # In case you would like to make changes to the theme and keep it locally in you repository,
  # uncomment the line below (and correct the local path if necessary).
  # --
  replacements = "github.com/hwajin-me/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = "terminal"